# Generated by Django 3.2 on 2023-03-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.competition')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='league.team')),
                ('visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitant', to='league.team')),
            ],
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
