# Generated by Django 3.2 on 2023-03-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='EventType',
            new_name='eventType',
        ),
    ]
