# Generated by Django 3.2 on 2023-03-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_rename_eventtype_event_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
