# Generated by Django 3.2 on 2023-03-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
